### ISSUE TITLE
Likely unintentional interaction with Sacrifice/Kin/Swarms artifacts

### ISSUE THREAD

**Issue by C-Stew** [redmushie/RedsSacrifice#2]
With the mod enabled, the sacrifice artifact seems to make every boss drop an item. Combining this with the artifacts of Kin and Swarms allows for upwards of 10 items per teleporter event.

For reference, I beat stage 8 in 27 minutes with 114 items, all but 5 of which were from teleporter events.
![image](https://user-images.githubusercontent.com/51380437/173606478-32a3fd0c-9d44-41f9-a3ee-3b2c1521b6b8.png)

**Comment by redmushie** [comment]
I apologize for the ridiculously late reply. I believe I fixed this in the latest commit. The version v1.1.2 should be available on Thunderstore as soon as it propagates. Thanks for the report :)
